# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jacques Loom Documentation
email: hello-world@read-only-memory.com
author: Norman Heck
description: > # this means to ignore newlines until "baseurl:"
  Documentation for the Jacques Loom Project

# Add your baseurl here (your repository)
baseurl: "/jacques-loom" # the subpath of your site, e.g. /blog

# This is mostly for testing
url: "https://festwertspeicher.github.io" # the base hostname & protocol for your site

# Keywords (space separated)
keywords: "jacques loom open hardware jacquard loom"

# Optional
# twitter: vsoch
# linkedin: vsochat
support: "mailto:hello-world@read-only-memory.com"
repo: https://github.com/festwertspeicher/jacques-loom
github_user: festwertspeicher
github_repo: jacques-loom
# discord: https://community.discord.com

# If you have a logo, put here to include in meta tags
# logo: assets/img/tw-jekyll.png

# branch to edit on GitHub
github_branch: main

# If not set, badge color (background) defaults to air
# badge_color: "#2bcf98"
badge_rounded: true

# Build settings
markdown: kramdown

# If you add tags to pages, define this variable to link them to some external search
# If you want to link to tags locally on the site, leave this commented out
# tag_search_endpoint: https://ask.cyberinfrastructure.org/search?q=
tag_color: primary # danger, success, warning, primary, info, secondary

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, _tailwind, Gemfile, Gemfile.lock, package-lock.json, package.json, postcss.config.js, tailwind.config.js, CHANGELOG.md, LICENSE, README.md, vendor, node_modules]

#sass compilation
sass:
  style: compressed

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
